// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitchDropsDiscordBot.Contexts;

#nullable disable

namespace TwitchDropsDiscordBot.Migrations
{
    [DbContext(typeof(TwitchDropsBotDbContext))]
    [Migration("20260414181907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.Drop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountLinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("account_link_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DetailsUrl")
                        .HasColumnType("text")
                        .HasColumnName("details_url");

                    b.Property<short>("DropOwnerId")
                        .HasColumnType("smallint")
                        .HasColumnName("drop_owner_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<short>("GameId")
                        .HasColumnType("smallint")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<short>("drop_owner_id")
                        .HasColumnType("smallint")
                        .HasColumnName("drop_owner_id");

                    b.Property<short>("game_id")
                        .HasColumnType("smallint")
                        .HasColumnName("game_id");

                    b.HasKey("Id")
                        .HasName("pk_drops");

                    b.HasIndex("drop_owner_id")
                        .HasDatabaseName("ix_drops_drop_owner_id");

                    b.HasIndex("game_id")
                        .HasDatabaseName("ix_drops_game_id");

                    b.ToTable("drops", null, t =>
                        {
                            t.Property("drop_owner_id")
                                .HasColumnName("drop_owner_id1");

                            t.Property("game_id")
                                .HasColumnName("game_id1");
                        });
                });

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.DropOwner", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_drop_owners");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_drop_owners_name");

                    b.ToTable("drop_owners", (string)null);
                });

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.Game", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<bool>("ShouldAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("should_alert");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_games_name");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.TimeBasedDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlertedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_on");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentDropId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_drop_id");

                    b.Property<short>("RequiredMinutesWatched")
                        .HasColumnType("smallint")
                        .HasColumnName("required_minutes_watched");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("parent_drop_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_drop_id");

                    b.HasKey("Id")
                        .HasName("pk_time_based_drops");

                    b.HasIndex("parent_drop_id")
                        .HasDatabaseName("ix_time_based_drops_parent_drop_id");

                    b.ToTable("time_based_drops", null, t =>
                        {
                            t.Property("parent_drop_id")
                                .HasColumnName("parent_drop_id1");
                        });
                });

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.Drop", b =>
                {
                    b.HasOne("TwitchDropsDiscordBot.Models.Entities.DropOwner", null)
                        .WithMany()
                        .HasForeignKey("drop_owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drops_drop_owners_drop_owner_id");

                    b.HasOne("TwitchDropsDiscordBot.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drops_games_game_id");
                });

            modelBuilder.Entity("TwitchDropsDiscordBot.Models.Entities.TimeBasedDrop", b =>
                {
                    b.HasOne("TwitchDropsDiscordBot.Models.Entities.Drop", null)
                        .WithMany()
                        .HasForeignKey("parent_drop_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_based_drops_drops_parent_drop_id");
                });
#pragma warning restore 612, 618
        }
    }
}
